[package]
name = "rs-riow"
version = "0.1.0"
authors = ["anticore <slimedev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.6.2"
rand = "0.7"